site_name: LightNet
site_dir: build/doc/lightnet

nav:
  - Home: index.md
  - Getting Started: Getting-Started.md
  - Documentation:
      - Project Structure: Documentation/Project-Structure.md
      - Build Options: Documentation/Build-Options.md
      - Intermediate Representation: Documentation/Intermediate-Representation.md
      - Operator Description: Documentation/Operator-Description.md
      - Miscellaneous: Documentation/Miscellaneous.md
  - Hacking: Hacking.md

repo_url: https://github.com/zhaozhixu/LightNet
edit_uri: ""

use_directory_urls: false

theme:
  name: mkdocs
  highlightjs: false

markdown_extensions:
  - toc:
      permalink: true
  - codehilite:
      guess_lang: false
  - def_list

extra_css:
  - css/codehilite.css
